
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SEMICOLON = 3;
  public static final int ELSE = 12;
  public static final int PLUS = 10;
  public static final int INT = 14;
  public static final int IDENTIFIER = 18;
  public static final int RETURN = 16;
  public static final int IF = 13;
  public static final int PUBLIC = 15;
  public static final int COMMA = 2;
  public static final int LESSTHAN = 8;
  public static final int EOF = 0;
  public static final int PRINTLN = 17;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int INTEGER = 19;
  public static final int ASSIGNMENT = 11;
  public static final int RIGHTPAREN = 7;
  public static final int LEFTPAREN = 6;
  public static final int RIGHTCURLY = 5;
  public static final int LEFTCURLY = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMICOLON",
  "LEFTCURLY",
  "RIGHTCURLY",
  "LEFTPAREN",
  "RIGHTPAREN",
  "LESSTHAN",
  "MINUS",
  "PLUS",
  "ASSIGNMENT",
  "ELSE",
  "IF",
  "INT",
  "PUBLIC",
  "RETURN",
  "PRINTLN",
  "IDENTIFIER",
  "INTEGER"
  };
}

